# Site settings
title: FalkirkLUG
email: admin@falkirklug.org
description: >
  FalkirkLUG (Linux User Group) is a group that meet monthly for fun
  techy discussions, along with a meal and a drink or two.Falkirklug
  is free to attend, so come along and see for yourself!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://falkirklug.github.io" # the base hostname & protocol for your site
twitter_username: gwmngilfen
github_username:  FalkirkLUG
gplus_url: https://plus.google.com/b/115476628113417487323/115476628113417487323/about

# Gmap settings
latitude: 56.0008123
longitude: -3.783533
zoom: 17

# Google Analytics
google_analytics_tracking_id: 'UA-43713039-2'

# Build settings
markdown: kramdown
